<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>EasyToolTip.Mau.ios</PackageId>
        <Title>EasyToolTip.Mau.ios</Title>
        <Authors>Emil Alipiev</Authors>
        <Description>EasyToolTip C# maui porting for iOS</Description>
        <PackageProjectUrl>https://github.com/EmilAlipiev/EasyToolTip.Mau.ios</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/EmilAlipiev/EasyToolTip.Mau.ios/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/EmilAlipiev/EasyToolTip.Mau.ios</RepositoryUrl>
        <PackageTags>maui ios xamarin </PackageTags>
        <RootNamespace>EastyToolTipMauiIos</RootNamespace>
        <PackageIcon>Tooltip.png</PackageIcon>
        <Version>1.0.1</Version>
    </PropertyGroup>
    <ItemGroup>
      <None Update="Tooltip.png">
        <Pack>True</Pack>      
      </None>
    </ItemGroup>
</Project>
